DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS item_requests;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    users_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    email varchar(20) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests (
    item_requests_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(1020) NOT NULL,
    requestor_id BIGINT REFERENCES users(users_id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    items_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(255) NOT NULL,
    available boolean NOT NULL,
    owner_id BIGINT REFERENCES users(users_id) ON DELETE CASCADE,
    request_id BIGINT REFERENCES item_requests(item_requests_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    bookings_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT REFERENCES items(items_id) ON DELETE CASCADE,
    booker_id BIGINT REFERENCES users(users_id) ON DELETE CASCADE,
    status varchar(8) NOT NULL,
    CONSTRAINT status_constraint CHECK (status = 'WAITING' OR status = 'APPROVED' OR status = 'REJECTED'
    OR status = 'CANCELED')
);

CREATE TABLE IF NOT EXISTS comments (
    comments_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(10200) NOT NULL,
    item_id BIGINT REFERENCES items(items_id) ON DELETE CASCADE,
    author_id BIGINT REFERENCES users(users_id) ON DELETE CASCADE,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);